### PR TITLE
Rework/Fix ESLint handling

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
- Replace eslintrc by new flat config
- Add ESLint dependencies to package.json
- Add test commands to package.json and README
- Handle linter issues

There are no functional changes.

### CODE REVIEW

**Comment by Tom-Hirschberger** [comment]
Hi and thank you for your contribution.
Great idea. I think i will adapt it to my other modules.

I only want to take a closer look to the changes in package.json ( the consequences of the name change in special) and the `const` declarations. I had a lot of problems with `const` and `var` in the past and changed nearly everything to `let` instead (even if `const` would be possible)

**Comment by Tom-Hirschberger** [comment]
Checked the `const` declarations and they look good to me.

Only one question left...
Did you change the package name in `package.json` to lower case or is this done by ESLint?

I do not have any glue if the change of the name has any consequences for the new module page or something else

**Comment by Tom-Hirschberger** [comment]
Hi,

i changed the base to development branch as i usually do not develop directly in the main branch. There is one conflict which needs to be fixed. 
I will take care about it as fast as i can.

**Comment by KristjanESPERANTO** [comment]
> and changed nearly everything to let instead (even if const would be possible)

I think that way would be totally okay too. We would only have to deactivate the ESLint rule "prefer-const" :slightly_smiling_face: 

> Did you change the package name in package.json to lower case or is this done by ESLint?

By hand. Upper case is not allowed in the name field: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#name

I use in other projects the ESLint plugin [eslint-plugin-package-json](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json), but since it has deprecated dependecies I don't introduce it into new projects.

> I do not have any glue if the change of the name has any consequences for the new module page or something else

I have looked at many MMM modules, but the name in the package.json did not matter in any of them. The lower case correction is just an act of nitpicking :smiley:

**Comment by KristjanESPERANTO** [comment]
> There is one conflict which needs to be fixed. I will take care about it as fast as i can.

I just resolved it.

**Comment by Tom-Hirschberger** [comment]
Thanks for solving the conflict.

Im fine with the changes now.

I can live with the `const` replacements, too.

Did some research today and misunderstood the meaning of `const` in the past. Now as i know the differences between `let` and `const` in know how to use it correct.

I will merge the changes to my dev branch now

**Pull request merged**
